// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;

      case TargetPlatform.windows:
        return windows;

      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
      case TargetPlatform.linux:
        throw UnsupportedError(
          'This platform is not configured for Firebase.',
        );

      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // 🔥 ANDROID CONFIG
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAozsW_scj4rHM4zemQhFdHY6n-o7bIkec',
    appId: '1:122933056130:android:8f82b231314579bc389a9b',
    messagingSenderId: '122933056130',
    projectId: 'port-7f3c1',
    storageBucket: 'port-7f3c1.firebasestorage.app',
  );

  // 💻 WINDOWS CONFIG
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDY0QAwN-y-bCCMSgILaGY7BQU28i1r5Mw',
    appId: '1:122933056130:web:47fa84c93ac9ffcb389a9b',
    messagingSenderId: '122933056130',
    projectId: 'port-7f3c1',
    authDomain: 'port-7f3c1.firebaseapp.com',
    storageBucket: 'port-7f3c1.firebasestorage.app',
    measurementId: 'G-F5NKG23KJP',
  );

  // 🌐 WEB CONFIG (THIS FIXES YOUR ERROR)
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY0QAwN-y-bCCMSgILaGY7BQU28i1r5Mw',
    appId: '1:122933056130:web:47fa84c93ac9ffcb389a9b',
    messagingSenderId: '122933056130',
    projectId: 'port-7f3c1',
    authDomain: 'port-7f3c1.firebaseapp.com',
    storageBucket: 'port-7f3c1.firebasestorage.app',
    measurementId: 'G-F5NKG23KJP',
  );
}